<a href="https://colab.research.google.com/github/pavi-ninjaac/Tensorflow_great_learning/blob/master/hello_world_tensorflow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import tensorflow as tf

In [2]:
import keras 

In [4]:
hello=tf.constant('hello world',name='hello')

In [6]:
print(hello)

tf.Tensor(b'hello world', shape=(), dtype=string)


In [7]:
hello_2=tf.constant('hello world',shape=[6,2])
print(hello_2)

tf.Tensor(
[[b'hello world' b'hello world']
 [b'hello world' b'hello world']
 [b'hello world' b'hello world']
 [b'hello world' b'hello world']
 [b'hello world' b'hello world']
 [b'hello world' b'hello world']], shape=(6, 2), dtype=string)


print hello world using the session

In [14]:
hello3=tf.constant(3,name='3',shape=[9,3])
print(hello3)

tf.Tensor(
[[3 3 3]
 [3 3 3]
 [3 3 3]
 [3 3 3]
 [3 3 3]
 [3 3 3]
 [3 3 3]
 [3 3 3]
 [3 3 3]], shape=(9, 3), dtype=int32)
